import { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'electronics',
    name: 'Electronics',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'fashion',
    name: 'Fashion',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'accessories',
    name: 'Accessories',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'lifestyle',
    name: 'Lifestyle',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=800',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Wolf Stealth Watch',
    price: 23999,
    description: 'A premium matte black timepiece designed for the modern predator. Water-resistant up to 100m with a sapphire crystal face.',
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=800',
    images: [],
    rating: 4.8,
    reviews: 124,
    stock: 15,
    featured: true,
  },
  {
    id: '2',
    name: 'Alpha Noise-Cancelling Headphones',
    price: 27999,
    description: 'Experience pure silence and high-fidelity sound. The Alpha series features active noise cancellation and 40-hour battery life.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800',
    images: [],
    rating: 4.9,
    reviews: 89,
    stock: 8,
    featured: true,
  },
  {
    id: '3',
    name: 'Midnight Leather Jacket',
    price: 47999,
    description: 'Handcrafted from premium full-grain leather. This jacket is built to last a lifetime and age beautifully.',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=800',
    images: [],
    rating: 4.7,
    reviews: 56,
    stock: 5,
    featured: true,
  },
  {
    id: '4',
    name: 'Wolf Pro Camera Bag',
    price: 14999,
    description: 'The ultimate companion for photographers on the move. Weatherproof, modular, and incredibly durable.',
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1544816153-12ad5d714481?auto=format&fit=crop&q=80&w=800',
    images: [],
    rating: 4.6,
    reviews: 42,
    stock: 20,
  },
  {
    id: '5',
    name: 'Shadow Tech Backpack',
    price: 11999,
    description: 'Minimalist design meets maximum functionality. Features a hidden laptop compartment and anti-theft zippers.',
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800',
    images: [],
    rating: 4.5,
    reviews: 78,
    stock: 12,
    featured: true,
  },
  {
    id: '6',
    name: 'Crimson Peak Sneakers',
    price: 9999,
    description: 'Bold red accents on a sleek white silhouette. Engineered for comfort and style.',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800',
    images: [],
    rating: 4.8,
    reviews: 210,
    stock: 25,
    featured: true,
  },
  {
    id: '7',
    name: 'Wolf Smart Speaker G2',
    price: 15999,
    description: 'Room-filling sound with integrated voice assistant. The heart of your smart home.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1589003077984-894e133dabab?auto=format&fit=crop&q=80&w=800',
    images: [],
    rating: 4.4,
    reviews: 67,
    stock: 30,
  },
  {
    id: '8',
    name: 'Obsidian Sunglasses',
    price: 12999,
    description: 'Polarized lenses with a lightweight titanium frame. Perfect for any outdoor adventure.',
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&q=80&w=800',
    images: [],
    rating: 4.7,
    reviews: 34,
    stock: 18,
  },
  {
    id: '9',
    name: 'Wolf Minimalist Wallet',
    price: 3999,
    description: 'RFID blocking, slim profile, and holds up to 12 cards. Made from aerospace-grade aluminum.',
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=800',
    images: [],
    rating: 4.9,
    reviews: 156,
    stock: 50,
  },
  {
    id: '10',
    name: 'Apex Performance Tee',
    price: 2999,
    description: 'Moisture-wicking fabric that moves with you. Designed for high-intensity training.',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800',
    images: [],
    rating: 4.6,
    reviews: 88,
    stock: 40,
  },
  {
    id: '11',
    name: 'Wolf Ultra Tablet',
    price: 63999,
    description: 'The most powerful tablet for creators. Features a 12.9-inch Liquid Retina XDR display and the M2 chip.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=800',
    images: [],
    rating: 4.9,
    reviews: 45,
    stock: 3,
    featured: true,
  },
  {
    id: '12',
    name: 'Stealth Running Shoes',
    price: 11999,
    description: 'Ultra-lightweight running shoes with carbon fiber plate for maximum energy return.',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800',
    images: [],
    rating: 4.7,
    reviews: 92,
    stock: 10,
    featured: true,
  },
  {
    id: 'test-1',
    name: 'Wolf Test Gear',
    price: 1,
    description: 'A special test product for payment verification. Limited edition for the pack alpha.',
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&q=80&w=800',
    images: [],
    rating: 5.0,
    reviews: 1,
    stock: 999,
    featured: true,
  },
];
